# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5efb4e293542a80368f86f5c8bc24744d36b713f1a22e8ff2220b37be0815199f0bc961dc1669d7dfeea1e8af17a32d3ac99a39f631274c20011c9d643c63d0c

test:
  secret_key_base: 2321e5a9744c52975bddc9ec2c864bce60971c80fc66b31697ba02851011ce5f8f027e0780809911ca9483e92a1752b8d60e72ea8399d3b4f7f648f6b7133a54

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
